
# 数据源
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/djmall?characterEncoding=UTF-8&useOldAliasMetadataBehavior=true&useSSL=false

#redis
  redis:
    host: localhost
    database: 0
    port: 6379

# Mybatis-plus
mybatis-plus:
  type-aliases-package: com.dj.mall.auth.entity # 类别名
  mapper-locations: classpath:/mapper/**/*.xml # mapper文件
  configuration:
    map-underscore-to-camel-case: true # 驼峰映射

# Dubbo
dubbo:
  application:
    name: auth-service # 应用名
    qos-enable: false # 关闭在线调试
  registry:
    address: zookeeper://localhost:2181 # 注册中心地址
  protocol:
    name: dubbo # 协议名
    port: 20880 # 服务端口
# 日志
logging:
  level:
    com.dj.mall.auth.mapper:
      debug

system:
  email:
    restPwd: 尊敬的%s，您的密码已被管理员%s，于%s重置为%s。为了您的账户安全，请及时修改。